basePath: /
host: localhost:3000
info:
  contact: {}
  description: API CRUD de Posts
  title: API GO CRUD
  version: "1.0"
paths:
  /posts:
    get:
      consumes:
      - application/json
      description: Consulta todos os post na base de dados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Consulta todos os post na base
    post:
      consumes:
      - application/json
      description: Inseri um novo post na base de dados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Inseri um novo post na base
  /posts:id:
    get:
      consumes:
      - application/json
      description: Consulta post pelo ID na base
      parameters:
      - description: Número 1
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Consulta post pelo ID na base
swagger: "2.0"
